# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PNRNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr_no', models.CharField(max_length=20)),
                ('notification_type', models.CharField(max_length=10)),
                ('notification_type_value', models.CharField(max_length=50)),
                ('notification_frequency', models.CharField(max_length=20)),
                ('notification_frequency_value', models.CharField(max_length=10)),
                ('next_schedule_time', models.DateTimeField()),
                ('notify_on_status_change', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PNRStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr_no', models.CharField(max_length=20)),
                ('status', jsonfield.fields.JSONField()),
            ],
        ),
    ]
