# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 07:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpanal', '0003_auto_20161026_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='userName',
            new_name='user',
        ),
    ]
