# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanal', '0006_auto_20161026_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='API_Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RailwayAPI_APIKEY', models.CharField(max_length=20)),
            ],
        ),
    ]
